### ISSUE TITLE
Editing of Title Pattern broken

### ISSUE THREAD

**Issue by berndl** [WissKI/wisski_pathbuilder#5]
Hi together!

I am working for a while now with one of your WissKI instances. The definition of title patterns for bundles has always worked fine, but now it seems to be broken.

I cannot choose paths anymore that would be used to define the pattern, as it would normally do when selecting an entry of the "Add a path" list:

![screen shot 2018-07-11 at 17 32 30](https://user-images.githubusercontent.com/7922417/42583202-cad38866-8530-11e8-813e-1a3a86c03745.png)

When accessing the edit title page for a bundle I get the following warning message (which prohibits the functionality, although it is only a warning):

`Warning: Invalid argument supplied for foreach() in Drupal\wisski_core\Form\WisskiTitlePatternForm->validateForm() (line 413 of /var/www/html/drupal/modules/wisski/wisski_core/src/Form/WisskiTitlePatternForm.php) #0 /var/www/html/drupal/core/includes/bootstrap.inc(566): _drupal_error_handler_real(2, 'Invalid argumen...', '/var/www/html/d...', 413, Array) #1 /var/www/html/drupal/modules/wisski/wisski_core/src/Form/WisskiTitlePatternForm.php(413): _drupal_error_handler(2, 'Invalid argumen...', '/var/www/html/d...', 413, Array) #2 [internal function]: Drupal\wisski_core\Form\WisskiTitlePatternForm->validateForm(Array, Object(Drupal\Core\Form\FormState)) #3 /var/www/html/drupal/core/lib/Drupal/Core/Form/FormValidator.php(83): call_user_func_array(Array, Array) #4 /var/www/html/drupal/core/lib/Drupal/Core/Form/FormValidator.php(274): Drupal\Core\Form\FormValidator->executeValidateHandlers(Array, Object(Drupal\Core\Form\FormState)) #5 /var/www/html/drupal/core/lib/Drupal/Core/Form/FormValidator.php(119): Drupal\Core\Form\FormValidator->doValidateForm(Array, Object(Drupal\Core\Form\FormState), 'wisski_bundle_t...') #6 /var/www/html/drupal/core/lib/Drupal/Core/Form/FormBuilder.php(571): Drupal\Core\Form\FormValidator->validateForm('wisski_bundle_t...', Array, Object(Drupal\Core\Form\FormState)) #7 /var/www/html/drupal/core/lib/Drupal/Core/Form/FormBuilder.php(314): Drupal\Core\Form\FormBuilder->processForm('wisski_bundle_t...', Array, Object(Drupal\Core\Form\FormState)) #8 /var/www/html/drupal/core/lib/Drupal/Core/Controller/FormController.php(74): Drupal\Core\Form\FormBuilder->buildForm('wisski_bundle_t...', Object(Drupal\Core\Form\FormState)) #9 [internal function]: Drupal\Core\Controller\FormController->getContentResult(Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\RouteMatch)) #10 /var/www/html/drupal/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #11 /var/www/html/drupal/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #12 /var/www/html/drupal/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #13 /var/www/html/drupal/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #14 [internal function]: Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #15 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Object(Closure), Array) #16 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #17 /var/www/html/drupal/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /var/www/html/drupal/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /var/www/html/drupal/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /var/www/html/drupal/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /var/www/html/drupal/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /var/www/html/drupal/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #23 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #24 /var/www/html/drupal/core/lib/Drupal/Core/DrupalKernel.php(657): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #25 /var/www/html/drupal/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #26 {main}. `

I could post another similar error that has to do with an input not being an array (saving it to not fully bloat this issue).

If it is any help, I suppose the last action I did was creating a new group and directly creating a bundle for that respective group (see pic below):
![screen shot 2018-07-11 at 17 27 24](https://user-images.githubusercontent.com/7922417/42582581-cd364b76-852f-11e8-9a71-4ac6e20aa537.png)

Deleting the newly created group did also not fix the issue. Title pattern editing for the other bundles is still broken.

Any ideas how I could resolve this? I would be very grateful :)

Thanks in advance, best,
Manu

**Comment by berndl** [comment]
Okay, for some reason it works again.. :)

Thanks, best,
Manu
